# Generated by Django 4.1.3 on 2023-01-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=200)),
                ('password2', models.CharField(max_length=200)),
                ('cname', models.CharField(max_length=500)),
                ('cindustry', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=200)),
                ('cpname', models.CharField(max_length=500)),
                ('cpmobile', models.CharField(max_length=20)),
                ('cpemail', models.EmailField(max_length=254)),
            ],
        ),
    ]
