# Generated by Django 4.1.3 on 2023-01-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_signup1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='', upload_to='images')),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
