# Generated by Django 4.1.3 on 2023-01-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_popular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popular',
            old_name='logo',
            new_name='logo1',
        ),
        migrations.RemoveField(
            model_name='popular',
            name='address',
        ),
        migrations.RemoveField(
            model_name='popular',
            name='company',
        ),
        migrations.RemoveField(
            model_name='popular',
            name='title',
        ),
        migrations.AddField(
            model_name='popular',
            name='address1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='popular',
            name='address2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='popular',
            name='address3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='popular',
            name='address4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='popular',
            name='cinfo1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='popular',
            name='cinfo2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='popular',
            name='cinfo3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='popular',
            name='cinfo4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='popular',
            name='company1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='popular',
            name='company2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='popular',
            name='company3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='popular',
            name='company4',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='popular',
            name='jinfo1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='popular',
            name='jinfo2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='popular',
            name='jinfo3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='popular',
            name='jinfo4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='popular',
            name='logo2',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='popular',
            name='logo3',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='popular',
            name='logo4',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='popular',
            name='title1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='popular',
            name='title2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='popular',
            name='title3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='popular',
            name='title4',
            field=models.CharField(default='', max_length=500),
        ),
    ]
